routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('socios.index');
});

Route::resource('socios','SocioController');
Route::resource('clubes','ClubeController');

app/Models/Clube.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Clube extends Model
{
    protected $table = 'clube';

    protected $fillable = ['nome'];

    public function socios()
    {
        return $this->belongsToMany(Socio::class)->withTimestamps();
    }
}

app/Models/Socio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Socio extends Model
{
    protected $table = 'socio';

    protected $fillable = ['nome'];

    public function clubes()
    {
        return $this->belongsToMany(Clube::class)->withTimestamps();
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ClubeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Clube;
use App\Http\Requests\ClubeRequest;

class ClubeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clubes = Clube::orderBy('nome');
        if($nome = request()->get('nome')){
            $clubes->where('nome','like','%'.$nome.'%');
        }
        $clubes = $clubes->paginate();

        return view('clubes.listar',compact('clubes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clubes.criar');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\ClubeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClubeRequest $request)
    {
        $dados =$request->all();
        $clube = Clube::create($dados);
        return redirect()->route('clubes.index')->with(['mensagem_sucesso'=>'Cadastrado com sucesso!']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Clube $clube)
    {
        return view('clubes.exibir',compact('clube'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Clube $clube)
    {
        return view('clubes.criar',compact('clube'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\ClubeRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ClubeRequest $request,Clube $clube)
    {
        $clube->fill($request->all());
        return redirect()->route('clube.index')->with(['mensagem_sucesso'=>'Cadastrado com sucesso!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Clube $clube)
    {
        $clube->delete();
        return response()->json(['deletado'=>1,'clube'=>$clube]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SocioController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SocioRequest;
use App\Models\Socio;
use App\Models\Clube;

class SocioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $socios = Socio::orderBy('nome');
        if($nome = request()->get('nome')){
            $socios->where('nome','like','%'.$nome.'%');
        }
        $socios = $socios->paginate();
        return view('socios.listar',compact('socios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clubes = Clube::orderBy('nome')->get();
        return view('socios.criar',compact('clubes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\SocioRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SocioRequest $request)
    {
        $socio = Socio::create($request->all());
        if($clubes = $request->get('clube_id')){
            $socio->clubes()->attach($clubes);
        }
        return redirect()->route('socios.index')->with(['mensagem_sucesso'=>'Cadastrado com sucesso!']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Socio $socio)
    {
        return view('socios.exibir',compact('socio'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Socio $socio)
    {
        return view('socios.criar',compact('socio'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\SocioRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SocioRequest $request,Socio $socio)
    {
        $socio->fill($request->all());
        return redirect()->route('socios.index')->with(['mensagem_sucesso'=>'Cadastrado com sucesso!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Socio $socio)
    {
        $socio->delete();

        return response()->json(['deletado'=>1,'socio'=>$socio]);
    }
}

resources/views/clubes/criar.blade.php
@extends('master')

@section('conteudo')
    <div class="card">
        <div class="card-header">
            Cadastrar clube
        </div>
        <div class="card-body">
            <form action="{{route('clubes.store')}}" method="post">
            {{csrf_field()}}
                <div class="form-row">
                    <div class="col mb-3">
                        <label for="nome">Nome</label>
                        <input type="text" class="form-control" placeholder="Nome" id="nome" value="" name="nome" required>
                    </div>
                </div>
                <div class="form-row">
                    <hr>
                    <button class="btn btn-primary" type="submit">Salvar</button>
                </div>
            </form>
        </div>
    </div>
@append

resources/views/clubes/listar.blade.php
@extends('master')

@section('conteudo')
<div class="card">
    <div class="card-header">
        <h1>Clubes</h1>
    </div>
    <div class="card-body">
        @if(session('mensagem_sucesso'))
        <div class="row">
            <div class="alert alert-success alert-dismissible fade show w-100" role="alert">
                {{session('mensagem_sucesso')}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        @endif
        <div class="row">
            <div class="col m-1">
                <form><input type="text" class="form-control" name="nome" placeholder="São Paulo.."></form>
            </div>
            <div class="col m-1">
            <div class="float-right">
                    <a href="{{route('clubes.create')}}" class="btn btn-primary">Cadastrar</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <table class="table">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Sócios</th>
                    <th scope="col" class="text-right">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($clubes as $clube)
                    <tr id="clube-{{$clube->id}}">
                        <td scope="row">{{$loop->index +1 }}</td>
                        <td>{{$clube->nome}}</td>
                        <td>{{$clube->socios()->count()}}</td>
                        <td class="text-right"><button data-link-delete="{{route('clubes.destroy',$clube)}}" data-tipo-elemento="clube" class="delete btn btn-danger">Deletar</button></td>
                    </tr>
                    @empty
                        <tr ><td class="text-center" colspan="4">Sem clubes cadastrados</td></tr>
                    @endforelse
                </tbody>
                </table>
                <div class="col">
                    {{$clubes->links()}}
                </div>
            </div>
        </div>
    </div>

</div>
@endsection

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet" type="text/css">
    <title>Dataclick teste</title>
    <link rel="stylesheet" href="{{ asset('/css/app.css') }}">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
</head>
<body>
    <header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{url('/')}}">Dataclick</a>
        <button class="navbar-toggler" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{route('clubes.index')}}">Clubes</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{route('socios.index')}}">Sócios</a>
            </li>
            </ul>
        </div>
    </nav>

    </header>
    <main class="container">
        @yield('conteudo')
    </main>
    <script src="{{ asset('/js/app.js') }}"></script>
</body>
</html>

resources/views/socios/criar.blade.php
@extends('master')

@section('conteudo')
    <div class="card">
        <div class="card-header">
            Cadastrar Sócio
        </div>
        <div class="card-body">
            <form action="{{route('socios.store')}}" method="post">
            {{csrf_field()}}
                <div class="form-row">
                    <div class="col mb-3">
                        <label for="nome">Nome</label>
                        <input type="text" class="form-control" placeholder="Nome" id="nome" value="{{$socio->nome ?? null}}" name="nome" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col mb-3">
                        <label for="nome">Clube</label>
                        <select class="bs-select" data-size="8" data-live-search="true" name="clube_id[]" multiple="multiple">
                            <option value="">Selecione um clube</option>
                            @foreach($clubes as $clube)
                                <option @if(isset($socio) && $socio->clubes->contains($clube->id)) selected  @endif value="{{$clube->id}}">{{$clube->nome}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-row">
                    <hr>
                    <button class="btn btn-primary" type="submit">Salvar</button>
                </div>
            </form>
        </div>
    </div>
@append

resources/views/socios/listar.blade.php
@extends('master')

@section('conteudo')
<div class="card">
    <div class="card-header">
        <h1>Sócios</h1>
    </div>
    <div class="card-body">
    @if(session('mensagem_sucesso'))
    <div class="row">
        <div class="alert alert-success alert-dismissible fade show w-100" role="alert">
            {{session('mensagem_sucesso')}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
    @endif
    <div class="row">
        <div class="col m-1">
            <form><input type="text" class="form-control" name="nome" placeholder="João.."></form>
        </div>
        <div class="col m-1">
            <div class="float-right">
                <a href="{{route('socios.create')}}" class="btn btn-primary">Cadastrar</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Clubes</th>
                <th scope="col" class="text-right">Ações</th>
                </tr>
            </thead>
            <tbody>
                @forelse($socios as $socio)
                <tr id="socio-{{$socio->id}}">
                    <td scope="row">{{$loop->index +1 }}</td>
                    <td>{{$socio->nome}}</td>
                    <td>{{$socio->clubes ? $socio->clubes->implode('nome',',')  :''}}</td>
                    <td class="text-right"><button data-link-delete="{{route('socios.destroy',$socio)}}" data-tipo-elemento="socio" class="delete btn btn-danger">Deletar</button></td>
                </tr>
                @empty
                    <tr ><td class="text-center" colspan="4">Sem sócios cadastrados</td></tr>
                @endforelse
            </tbody>
            </table>
            <div class="col">
                {{$socios->links()}}
            </div>
        </div>
    </div>
</div>
@endsection